adding agent conf to telegraf.conf
vito/telegraf-agent-boshrelease pull request #2
Opened 2019-04-10 20:39 UTC by kcmannem

Telegraf uses alot of resources, we need some knobs in our agent

Signed-off-by: Krishna Mannem <kmannem@pivotal.io>

2019-04-12 21:28 UTC, vito commented
fyi there are two bosh releases - one for use as a BOSH addon and one for configuring another agent to co-locate without conflicting with the addon.

this release is for the latter case - for the former, you may want to PR this here too: https://github.com/vito/telegraf-boshrelease

2019-04-12 21:30 UTC, vito requested changes

2019-04-12 21:30 UTC, vito commented on jobs/telegraf-agent/spec
> +  agent_conf:
🤔 should we instead add an explicit property or properties for what we're trying to expose?

alternatively, could we just call this `agent` so it matches the config scheme of the other properties? (pretty much 1:1 to the .ini values they set)

2019-05-03 18:56 UTC, kcmannem commented
Telegraf only uses resources badly **only** when we start swapping. We were just biased into believing it was bad because we only observed it when workers were in bad state. 

I'm going to re-pr this when we need it.

2019-05-03 18:56 UTC, closed without merging